### ISSUE TITLE
panic in Windows environment

### ISSUE THREAD

**Issue by tesujiro** [tesujiro/exp_yacc#4]
```
panic: open /dev/tty: The system cannot find the path specified.

goroutine 1 [running]:
panic(0x4ac880, 0x115f7b40)
        C:/Go/src/runtime/panic.go:500 +0x331
main.main()
        H:/go/src/github.com/tesujiro/exp_yacc/interpretor.go:18 +0x69
```

**Comment by tesujiro** [comment]
Can not reproduce
